# Generated by Django 5.2.11 on 2026-02-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
