# Generated by Django 5.2.11 on 2026-02-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginOTP',
        ),
    ]
